### ISSUE TITLE
Incorrect filename in test

### ISSUE THREAD

**Issue by seesemichaelj** [gitcoinco/BulkTransactions#9]
In the `add-zksync-contract` branch, https://github.com/gitcoinco/BulkTransactions/blob/add-zksync-contract/test/batch-zkSync-deposit-test.js#L6 has an incorrect contract name. it should be `BatchZkSyncDeposit` (just change the first letter to a capital B). I'm guessing you're developing on Windows where that would translate to the same file? Linux and Mac are case-sensitive with filenames however and running the test gives  the following error:

```
Error: /home/mike/work/truffle/BulkTransactions/build/contracts/batchZkSyncDeposit.json: ENOENT: no such file or directory, open '/home/mike/work/truffle/BulkTransactions/build/contracts/batchZkSyncDeposit.json'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Object.readFileSync (/home/mike/work/truffle/BulkTransactions/node_modules/jsonfile/index.js:61:22)
    at loadArtifact (/home/mike/work/truffle/BulkTransactions/node_modules/@openzeppelin/test-environment/node_modules/@openzeppelin/contract-loader/lib/index.js:47:23)
    at TruffleLoader.BaseLoader.fromArtifact (/home/mike/work/truffle/BulkTransactions/node_modules/@openzeppelin/test-environment/node_modules/@openzeppelin/contract-loader/lib/index.js:65:18)
    at Object.<anonymous> (/home/mike/work/truffle/BulkTransactions/test/batch-zkSync-deposit-test.js:6:37)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.exports.requireOrImport (/home/mike/work/truffle/BulkTransactions/node_modules/mocha/lib/esm-utils.js:20:12)
    at Object.exports.loadFilesAsync (/home/mike/work/truffle/BulkTransactions/node_modules/mocha/lib/esm-utils.js:33:34)
    at Mocha.loadFilesAsync (/home/mike/work/truffle/BulkTransactions/node_modules/mocha/lib/mocha.js:427:19)
    at singleRun (/home/mike/work/truffle/BulkTransactions/node_modules/mocha/lib/cli/run-helpers.js:156:15)
    at exports.runMocha (/home/mike/work/truffle/BulkTransactions/node_modules/mocha/lib/cli/run-helpers.js:225:10)
    at Object.exports.handler (/home/mike/work/truffle/BulkTransactions/node_modules/mocha/lib/cli/run.js:366:11)
    at innerArgv.then.argv (/home/mike/work/truffle/BulkTransactions/node_modules/yargs/lib/command.js:241:49)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
error Command failed with exit code 1
```

**Comment by mds1** [comment]
Thanks, just pushed a commit to that branch which fixes that

But oddly enough I'm on macOS 10.15.6, and even with the lowercase "b" the tests run for me

**Comment by seesemichaelj** [comment]
I [stand corrected](https://www.quora.com/Why-does-OS-X-choose-to-have-a-case-insensitive-file-system-instead-of-a-case-sensitive-one); I guess it's only Linux that uses case-sensitive lol. I thought it was a generic Unix thing.

**Comment by mds1** [comment]
Huh, never knew about partial case-insensitivity. Thanks for sharing, that is interesting!
